version: '3.8'

services:
  db:
    image: postgres:17
    container_name: tutor-app-db
    environment:
      POSTGRES_DB: tutor-app-db
      POSTGRES_USER: tutorappuser
      POSTGRES_PASSWORD: tutorapppassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: